import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "./component/Navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        <header className="bg-blue-800 py-4 text-white flex justify-evenly">
          <h1>My Website</h1>
          <Navigation/>

        </header>
        {children}
      <footer className="bg-blue-800 py-3  text-white flex justify-center"> 
        <p>
         © 2025 My Website
        </p>
      </footer>
      </body>

    </html>
  );
}
